$ANSIBLE_VAULT;1.1;AES256
34363038376234346162333634646362363231346631363632303330663661633038623232656364
3137353337616133396135353233613332306134303761380a386566363632383331306665623864
39636437326336306136623632383831636430643138613063626235373066383034383437303937
6632643830643538390a316566396361326335363731333361363734326533336364323662626262
63633262343439326361346439393937306364663233336165353337366334333266313263336137
30326166656132623430336261303436303938363937353231363036333436383532326564393637
63663831653934653932633433303864363266353463363431376231336339343664666363356330
38313932323063376631626632633037353532386365376539643532616637313966623133336539
36316431303637643433653636393939346165623265326431633737366666663264393164353739
33323739623239626235393861323466366136383339656266646532363635663761613262373162
33636236383833346236633562616162393636353363633364313236306437313039643264643665
30633034383036383961613666306166363563623464363030343735326366323162646464366366
3237
